fixed md module load traj func for bond recalc on line 110
janash/MolecularNodes pull request #11
Opened 2023-03-11 17:35 UTC by kimjoyc

2023-03-11 17:45 UTC, kimjoyc commented
Fixing the bug related to partial selection of a molecule when using Ball and Stick resulting in Blender crash.
The crash in the load_trajectory function in md.py is due selections using MDAnalysis, references to atoms that are not in the selection are left in the bond list.

A solution to resolve this is to reorder the bond indices when residues or fragments are not next to each other and discard bonding where an atom is missing.

2023-03-11 18:57 UTC, janash requested changes
Looks good. Just a few small changes on the code itself.

When you file the PR on the real repo, make sure to say something like "Fixes #ISSUE_NUMBER" where ISSUE_NUMBER is the number of your issue (you will need the `#`). This will link to the issue filed earlier and should automatically close it when the PR is merged.

2023-03-11 18:57 UTC, janash commented on MolecularNodes/md.py
> +    # if hasattr(univ, 'bonds') and include_bonds:
You can delete these lines which are commented out. If the bug fix is adopted, they shouldn't be kept in the file

2023-03-11 18:57 UTC, janash commented on MolecularNodes/md.py
> +    ##BUGFIX
You don't need this `##BUGFIX` comment in the real PR.

2023-03-12 00:19 UTC, janash approved these changes
Be careful with your git commit messages. It should be more descriptive than "removes"

2023-03-15 16:01 UTC, closed without merging